package telas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joaoc
 */
public class telaAgendarExame2 extends javax.swing.JFrame {

    /**
     * Creates new form telaAgendarExame2
     */
    public telaAgendarExame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        lblSelecionarEnfermeiro = new javax.swing.JLabel();
        rbtnExame = new javax.swing.JRadioButton();
        rbtnVacina = new javax.swing.JRadioButton();
        lblAgendar = new javax.swing.JLabel();
        cbTipoExameVacina = new javax.swing.JComboBox<>();
        lblTipoExameVacina = new javax.swing.JLabel();
        txtEnfermeiro = new javax.swing.JTextField();
        lblHorário = new javax.swing.JLabel();
        iconSexoPaciente = new javax.swing.JLabel();
        iconTipoExameVacina = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        lblSelecionarPaciente = new javax.swing.JLabel();
        lblDataAtual = new javax.swing.JLabel();
        lblAgendadoEm1 = new javax.swing.JLabel();
        txtHorarioAgendamento = new javax.swing.JTextField();
        lblMarcadoPara1 = new javax.swing.JLabel();
        txtDataAgendamento = new javax.swing.JTextField();
        btnAvancar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(248, 197, 190));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(153, 0, 0));
        txtTitle.setText("Agendamento de Exames e Vacinas");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addComponent(txtTitle)
                .addGap(283, 283, 283))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtTitle)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        background.add(panelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        lblSelecionarEnfermeiro.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblSelecionarEnfermeiro.setText("Selecionar enfermeiro:");
        background.add(lblSelecionarEnfermeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 210, 40));

        rbtnExame.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnExame.setText("Exame");
        background.add(rbtnExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        rbtnVacina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnVacina.setText("Vacina");
        background.add(rbtnVacina, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        lblAgendar.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblAgendar.setText("Agendar:");
        background.add(lblAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 100, 40));

        cbTipoExameVacina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTipoExameVacina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoExameVacinaActionPerformed(evt);
            }
        });
        background.add(cbTipoExameVacina, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 150, 30));

        lblTipoExameVacina.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblTipoExameVacina.setText("Tipo:");
        background.add(lblTipoExameVacina, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 100, 40));

        txtEnfermeiro.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtEnfermeiro.setText("Jorginho Vasquez");
        background.add(txtEnfermeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 210, 30));

        lblHorário.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblHorário.setText("Horário:");
        background.add(lblHorário, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 210, 40));

        iconSexoPaciente.setText("IconSexo");
        background.add(iconSexoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));

        iconTipoExameVacina.setText("IconOption");
        background.add(iconTipoExameVacina, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        txtPaciente.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtPaciente.setText("João Carlos Gonçalves");
        background.add(txtPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 210, 30));

        lblSelecionarPaciente.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblSelecionarPaciente.setText("Selecionar paciente:");
        background.add(lblSelecionarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 210, 40));

        lblDataAtual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDataAtual.setText("Data atual");
        background.add(lblDataAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));

        lblAgendadoEm1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblAgendadoEm1.setText("Marcado em: ");
        background.add(lblAgendadoEm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 210, 40));

        txtHorarioAgendamento.setText("horário agendamento");
        background.add(txtHorarioAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 140, 30));

        lblMarcadoPara1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblMarcadoPara1.setText("Agendado para:");
        background.add(lblMarcadoPara1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 210, 40));

        txtDataAgendamento.setText("data de agendamento");
        background.add(txtDataAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 140, 30));

        btnAvancar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAvancar.setText("Avançar");
        background.add(btnAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 570, 190, 60));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoExameVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoExameVacinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoExameVacinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaAgendarExame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaAgendarExame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaAgendarExame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaAgendarExame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaAgendarExame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JComboBox<String> cbTipoExameVacina;
    private javax.swing.JLabel iconSexoPaciente;
    private javax.swing.JLabel iconTipoExameVacina;
    private javax.swing.JLabel lblAgendadoEm1;
    private javax.swing.JLabel lblAgendar;
    private javax.swing.JLabel lblDataAtual;
    private javax.swing.JLabel lblHorário;
    private javax.swing.JLabel lblMarcadoPara1;
    private javax.swing.JLabel lblSelecionarEnfermeiro;
    private javax.swing.JLabel lblSelecionarPaciente;
    private javax.swing.JLabel lblTipoExameVacina;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JRadioButton rbtnExame;
    private javax.swing.JRadioButton rbtnVacina;
    private javax.swing.JTextField txtDataAgendamento;
    private javax.swing.JTextField txtEnfermeiro;
    private javax.swing.JTextField txtHorarioAgendamento;
    private javax.swing.JTextField txtPaciente;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
