package telas;

public class telaAgendarExame extends javax.swing.JFrame {

    /**
     * Creates new form telaAgendarExame2
     */
    public telaAgendarExame() {
        initComponents();
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jComboBox1 = new javax.swing.JComboBox<>();
        background = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        lblSelecionarEnfermeiro = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        lblSelecionarPaciente = new javax.swing.JLabel();
        btnAvancar = new javax.swing.JButton();
        iconSexoPaciente1 = new javax.swing.JLabel();
        tblCheckOut = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdicionarExame = new javax.swing.JButton();
        btnAdicionarVacina = new javax.swing.JButton();
        lblSelecionarPaciente1 = new javax.swing.JLabel();
        iconSexoPaciente2 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(248, 197, 190));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(153, 0, 0));
        txtTitle.setText("Agendamento - Exames e Vacinas");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(txtTitle)
                .addContainerGap(477, Short.MAX_VALUE))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(txtTitle)
                .addGap(18, 18, 18))
        );

        background.add(panelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 70));

        lblSelecionarEnfermeiro.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblSelecionarEnfermeiro.setText("Check-out:");
        background.add(lblSelecionarEnfermeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, 40));

        txtPaciente.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        background.add(txtPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 220, 40));

        lblSelecionarPaciente.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblSelecionarPaciente.setText("Adicionar:");
        background.add(lblSelecionarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 210, 40));

        btnAvancar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAvancar.setText("Avançar");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });
        background.add(btnAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 180, 50));

        iconSexoPaciente1.setText("iconVacinaExame");
        background.add(iconSexoPaciente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Procedimento", "Tipo", "Enfermeiro", "Valor"
            }
        ));
        tblCheckOut.setViewportView(jTable1);

        background.add(tblCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 640, 220));

        btnAdicionarExame.setText("Exame");
        background.add(btnAdicionarExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 90, 40));

        btnAdicionarVacina.setText("Vacina");
        background.add(btnAdicionarVacina, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 100, 40));

        lblSelecionarPaciente1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        lblSelecionarPaciente1.setText("Selecionar paciente:");
        background.add(lblSelecionarPaciente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 210, 40));

        iconSexoPaciente2.setText("IconSexo");
        background.add(iconSexoPaciente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, 20));

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        background.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        // TODO add your handling code here:
        telaPagamento telaPag = new telaPagamento(this);
        telaPag.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAvancarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaAgendarExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaAgendarExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaAgendarExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaAgendarExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaAgendarExame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAdicionarExame;
    private javax.swing.JButton btnAdicionarVacina;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel iconSexoPaciente1;
    private javax.swing.JLabel iconSexoPaciente2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSelecionarEnfermeiro;
    private javax.swing.JLabel lblSelecionarPaciente;
    private javax.swing.JLabel lblSelecionarPaciente1;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JScrollPane tblCheckOut;
    private javax.swing.JTextField txtPaciente;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
